steps:

- id: "Running docker-compose"
  name: 'gcr.io/$PROJECT_ID/docker-compose'
  args: ['-f','docker-compose-cloudbuild.yml','up','-d']

- id: "Running PS"
  name: 'gcr.io/cloud-builders/docker'
  args: ['ps']  

- id: "Chown in /var/www/storage"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-u','root','-t','app','chown','-R','www-data:www-data','/var/www/storage']

- id: "Chmod /var/www/storage"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-u','root','-t','app','chmod','0777','/var/www/storage','-R']

- id: "Mkdir /var/www/bootstrap/cache"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-t','app','mkdir','-p','/var/www/bootstrap/cache']

- id: "Chmod /var/www/bootstrap/cache"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-u','root','-t','app','chmod','1777','/var/www/bootstrap/cache','-R']

- id: "Running composer"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-t','app','composer','install']  

- id: "Copying .env"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-u','root','-t','app','cp','-f','.env.example','.env']    

- id: "Chown .env"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-u','root','-t','app','chown','www-data.www-data','.env']


- id: "Running key:generate"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-t','app','php','/var/www/artisan','key:generate']    

- id: "Running migrate"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-t','app','php','/var/www/artisan','migrate']

- id: "Running phpunit"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-t','app','php','/var/www/vendor/bin/phpunit','-c','/var/www/phpunit.xml']